[package]
name = "fromsoftware-dlrf"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = false
description = "Macro for generating singleton specifier for usage with the DLRF singleton finder"

[dependencies]
dlrf-derive.workspace = true
